### ISSUE TITLE
Unable to play Master Playlist

### ISSUE THREAD

**Issue by spd789562** [goldvideo/h265player#15]
The M3U8Parser will throw `Parse playlist error.`, cause it skips handling `EXT-X-STREAM-INF` and doesn't read Media playlist.

And I found a missing letter in this line. It should be `streamInf`
https://github.com/goldvideo/h265player/blob/14fb1d8e89558cff3f368a4cf945690236343376/src/toolkit/M3U8Parser.js#L37

**Comment by jarry** [comment]
ok.thank you. it's has solved.
