### ISSUE TITLE
Bad reference to ImagePlayer directory in Player.js

### ISSUE THREAD

**Issue by joefriel** [goldvideo/h265player#4]
https://github.com/goldvideo/h265player/blob/df9e1c343c10b4cd43e13cf576ac425b56ad1948/src/Player.js#L26

The directory is named imageplayer

**Comment by yiwen03** [comment]
thank you. the path should ./imagePlayer/, now have fixed

**Comment by joefriel** [comment]
path should be ./imageplayer/  (all lowercase) ??

**Comment by yiwen03** [comment]
yes ,the path is ./imageplayer/
