### ISSUE TITLE
decoder_wasm 编译的libffmpeg.js在这边不能通用吧。

### ISSUE THREAD

**Issue by fzw2408** [goldvideo/h265player#46]
作者你好，这个项目单纯的只支持h265.有没有 同时支持h264 h265 的lib库，h265player的lib库会不会开源出啦？

**Comment by snxly** [comment]
参考 decoder_wasm 的 readme

进入代码目录，根据需要，以下命令三选一执行：

./build_decoder_264.sh      //支持解码 H.264
./build_decoder_265.sh      //支持解码 H.265
./build_decoder_264_265.sh  //支持解码 H.264 和 H.265

**Comment by fzw2408** [comment]
我编译出的libffmpeg_264_265.js ===》libffmpeg.js 替换了h265player dist下的对应的 libffmpeg.js 和libffmpeg.wasm. 并不适用。我的目的是想实现：http下载分片。 libffmpeg.wasm 解码 264 或者 265。 这样我们就不用在用个浏览器的播放器去播放 h264. 我知道
./build_decoder_264_265.sh  可以实现 264 和265的解码。但是在h265player 用不上。希望各位大佬指点下小弟。

**Comment by snxly** [comment]
如果需要播放H264的码流，需要在初始化decoder的时候指定编码格式
https://github.com/goldvideo/h265player/blob/master/src/decode/FFmpegDecode.js#L42
Module._openDecoder(0, videoCallback, 1) // 0 - H.264, 1 - H.265, 默认是H.265
----
https://github.com/goldvideo/decoder_wasm#33-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
var codecType = 1; // 0 - H.264, 1 - H.265
var ret = Module._openDecoder(codecType, videoCallback, LOG_LEVEL_WASM)

**Comment by fzw2408** [comment]
got it ！非常感谢 anxly  小结一下：  
1.decode_wasm 解码器编译出来的 wasm文件是可以用的。 libffmpeg_264_265.wasm
2. var codecType = 1; // 0 - H.264, 1 - H.265
    var ret = Module._openDecoder(codecType, videoCallback, LOG_LEVEL_WASM)
3.h265player 中改成h264player
### https://github.com/goldvideo/h265player/blob/master/src/demux/TsDemux.js 
tsDemuxed(data) {
    let streamType = data.stream_type
    let pes = data.pes || {}
    switch (streamType) {       
      **case 27:  //h264
        this.videoQueue(pes)
        break**     
      case 36: //  265
        this.videoQueue(pes)
        break
      case 3:
      case 15:
      case 17:
        pes.PTS = Math.round(pes.PTS * AV_TIME_BASE_Q * 1000)
        this.maxAudioPTS = Math.max(pes.PTS, this.maxAudioPTS)
        this.audioQueue(pes)
        break
      default: 
        break
    }
**4. 还有一个小问题。就是直接取到流以后判断一下码流动态设置一下 
    Module._openDecoder(0, videoCallback, 1) // 0 - H.264, 1 - H.265, 默认是H.265**
