### ISSUE TITLE
解码音频的时候，为什么把一个ts 包里的音频buffer，放到一个arraybuffer 再解码，而不是收到一个音频buffer，直接解码

### ISSUE THREAD

**Issue by takeern** [goldvideo/h265player#50]
请教下，解码音频的时候，为什么把一个ts 包里的音频buffer，放到一个arraybuffer 再解码，而不是收到一个音频buffer，直接解码？
我试图收到一个音频buffer 直接做解码，然后去播放，声音会失真。
![image](https://user-images.githubusercontent.com/12117721/105964013-9f707e80-60bc-11eb-9f7a-ae0678fb6247.png)

**Comment by snxly** [comment]
观察一下解码后的this.audioBuffer，印象里解码完成的数据会被清空，有可能有一些没有完全解码的数据残留。
