### ISSUE TITLE
可以支持rtmp流吗？

### ISSUE THREAD

**Issue by Qianxunha** [goldvideo/h265player#7]
博主你好，想问下该播放器可以支持rtmp流吗，支持h.265/h.264编码
推流端：走的rtmp协议，推送h.264/h.265裸流到 srs/nginx-rtmp-server 服务器
拉流端：用你的播放器可以支持rtmp流吗？
小白刚入行

**Comment by yiwen03** [comment]
不支持rtmp协议

**Comment by Qianxunha** [comment]
@yiwen03  感谢博主解答，请问有什么方法可以支持rtmp流吗

**Comment by yiwen03** [comment]
支持rtmp需要用到flash，h5是不支持的

**Comment by Qianxunha** [comment]
@yiwen03  rtmp流可以转成http-flv流吗

**Comment by Qianxunha** [comment]
@支持播放http-flv流吗，目前已将rtmp流转成http-flv流，博主的播放器支持什么协议
